#!/bin/bash
#$ -N PoseCorrNets-test-pretrained
#$ -l h_rt=6:00:00
#$ -l gpu=1
#$ -o /home/zcemjml/Scratch/simcol/bimodal_camera_pose/logs/test/
#$ -e /home/zcemjml/Scratch/simcol/bimodal_camera_pose/logs/test/

# directories for storing output & error log files must exist

cd /home/zcemjml/Scratch/simcol/bimodal_camera_pose  # working directory of test.py

python test.py \
    '../SyntheticColon_I/' \
    --pretrained_posenet './trained_models/posenet_binned/' \
    --test-file 'test_file.txt'