#!/bin/bash
#$ -N simcol-test-pretrained
#$ -l h_rt=12:00:00
#$ -l gpu=1
#$ -o /home/zcemjml/Scratch/simcol/bimodal_camera_pose/logs/test/
#$ -e /home/zcemjml/Scratch/simcol/bimodal_camera_pose/logs/test/

source /home/zcemjml/anaconda3/etc/profile.d/conda.sh
conda activate pytorch-simcol

cd /home/zcemjml/Scratch/simcol/bimodal_camera_pose 

python test.py \
    ../SyntheticColon_I/ \
    --test-file ./data/test_file.txt